---
- hosts: all
  become: true
  tasks:
      - name: Make a 'wheel' group
        group:
          name: wheel
          state: present

      - name: Allow 'wheel' group to have passwordless sudo
        lineinfile:
          dest: /etc/sudoers
          state: present
          regexp: '^%wheel'
          line: '%wheel ALL=(ALL) NOPASSWD: ALL'
          validate: 'visudo -cf %s'

      - name: Add new user, scoopadmin, to wheel group
        user: name=scoopadmin groups=wheel shell=/bin/bash append=yes state=present createhome=yes

      - name: Set up authorized keys for the user
        authorized_key: user=scoopadmin key="{{item}}"
        with_file:
          - ~/.ssh/id_rsa.pub
      
      - name: Disable root access
        lineinfile:
          dest: /etc/ssh/sshd_config
          regexp: '^PermitRootLogin'
          line: 'PermitRootLogin no'
          
      - name: Restart sshd
        service:
          name: 'ssh'
          state: 'restarted'
    
      - name: Update apt-cache 
        apt: update_cache=yes
      
      - name: Install Nginx, fail2ban
        apt: name={{ item }} state=latest
        with_items:
          - nginx
          - fail2ban
          
      - name: Setup firewall
        ufw:
          rule: allow
          name: Nginx HTTP
          
      - name: Setup firewall
        ufw:
          rule: allow
          name: OpenSSH
        
      - name: Enable firewall
        ufw: 
          state: enabled
     
      - name: Set html
        copy:
           src: index.html
           dest: /var/www/html/index.nginx-debian.html
           mode: u+rw
          
     # Password protect
