---
- hosts: all
  become: true
  tasks:
      - name: Make sure we have a 'wheel' group
        group:
          name: wheel
          state: present

      - name: Allow 'wheel' group to have passwordless sudo
        lineinfile:
          dest: /etc/sudoers
          state: present
          regexp: '^%wheel'
          line: '%wheel ALL=(ALL) NOPASSWD: ALL'
          validate: 'visudo -cf %s'

      - name: Add sudoers users to wheel group
        user: name=scoopadmin groups=wheel append=yes state=present createhome=yes

      - name: Set up authorized keys for the user
        authorized_key: user=scoopadmin key="{{item}}"
        with_file:
          - ~/.ssh/id_rsa.pub
      # # Create a new superuser
      # - name: Create superuser
      #   command: adduser greg1
      # 
      # # Add ssh public key
      # - name: copy ssh key
      #   authorized_key:
      #     key: "{{ lookup('file', ssh_key) }}"
      #     user: scoop
      
      # Disable password login and root login
      - name: Enabling ssh-key only root access
        lineinfile:
          dest: /etc/ssh/sshd_config
          regexp: '^PermitRootLogin'
          line: 'PermitRootLogin without-password'
    
      - name: Update apt-cache 
        apt: update_cache=yes
      
      - name: Install Nginx, iptables, fail2ban
        apt: name={{ item }} state=latest
        with_items:
          - nginx
          - fail2ban
          
      # Setup firewall
      - name: Setup firewall
        ufw:
          rule: allow
          name: Nginx HTTP
          
      - name: Setup firewall
        ufw:
          rule: allow
          name: OpenSSH
        
      - name: Enable firewall
        ufw: 
          state: enabled
     
     # Setup nginx webserver with new html
      - name: Set html
        copy:
           src: index.html
           dest: /var/www/html/index.nginx-debian.html
           mode: u+rw
          
     # Password protect
